### ISSUE TITLE
bug: Autocompletion with slash bug with tsx.

### ISSUE THREAD

**Issue by chaozwn** [windwp/nvim-ts-autotag#125]
with autocomplete always return /div>.

https://github.com/windwp/nvim-ts-autotag/assets/51357674/ea34e54c-d84b-4cc7-834b-2583e5754afb

**Comment by Naught0** [comment]
I have this problem as well. It appears doing a self-closing tag e.g. `<br />` will result in an attempt to close the closest parent tag. In your case, that is `div`.

<img width="312" alt="image" src="https://github.com/windwp/nvim-ts-autotag/assets/4589250/11525d50-6882-4df0-8f4f-4dc4d5e4f416">
This is an example of what happens when I try to close `<Input />`

**Comment by Callumk7** [comment]
I have this issue as well.

**Comment by bkerz** [comment]
I have this issue too. Callum7's solution worked perfectly for me, but I just want to mention I tried to fix it in the same way using 
```
				require "nvim-ts-autotag".setup {
					autotag = {
						enable = true,
						enable_rename = true,
						enable_close_on_slash = false,
					}
				}

```
But it seems this config wasn't read, only the treesitter config. Don't know if this is an issue as well, but I'll leave it here.

**Comment by meronogbai** [comment]
Callum7's solution worked for me too. Shouldn't that option be set to false by default?

**Comment by bartels** [comment]
This bug still exists.  Disabling the feature with `enable_close_on_slash = false` is the current workaround
