### ISSUE TITLE
can you make it work for htmldjango files?

### ISSUE THREAD

**Issue by Reficulx** [windwp/nvim-ts-autotag#127]
Hey, hello, I am just wondering if you could make it work with htmldjango files, thanks

**Comment by barrett-ruth** [comment]
Oddly enough, even with htmldjango specified in the filetypes, the plugin doesn't actually run on the files. Unsure why this is and I think it actually is a bug.

**Comment by barrett-ruth** [comment]
Seems like because of [right here](https://github.com/windwp/nvim-ts-autotag/blob/6be1192965df35f94b8ea6d323354f7dc7a557e4/lua/nvim-ts-autotag/internal.lua#L70) where htmldjango files are categorized as handlebars tags, which (I'm guessing) prevents normal html tags from working (when, obviously, we need both).

**Comment by barrett-ruth** [comment]
Ok, since because "htmldjango" is included in the HBS_TAG filetypes, the fact that it is also in "HTML_TAG" gets overidden in [this method](https://github.com/windwp/nvim-ts-autotag/blob/6be1192965df35f94b8ea6d323354f7dc7a557e4/lua/nvim-ts-autotag/internal.lua#L137), which I think effectively excludes any html tag behavior from being performed.

For now I just remove "htmldjango" from the HBS_TAG variable.

**Comment by matthewmazzanti** [comment]
@barrett-ruth Made a fork with your change, which fixed it. Up in #135

**Comment by barrett-ruth** [comment]
Thanks. This project needs more active people to merge prs like this that are one word long.

**Comment by mstendorf** [comment]
Would be very nice if this could be merged soonish.
