### ISSUE TITLE
Lazy-loading doesn't work

### ISSUE THREAD

**Issue by savchenko** [windwp/nvim-ts-autotag#193]
Lazy-loading via "Lazy" plugin manager doesn't seem to work. Can be reproduced by adding the following 2 lines to the plugin spec:
```lua
lazy = true,
ft = { 'html' }
```

...and opening an HTML file.

**Comment by PriceHiller** [comment]
Might be because we depend on the `Filetype` event to attach `nvim-ts-autotag`.

Please read the note on lazy loading [here](https://github.com/windwp/nvim-ts-autotag?tab=readme-ov-file#a-note-on-lazy-loading).

`nvim-ts-autotag` is pretty efficient on deciding when to attach, lazy loading it shouldn't really impact startup time at all. If you insist on lazy loading, read the linked section and avoid anything that might interfere with picking up on `Filetype` events.
