### ISSUE TITLE
Auto Indent

### ISSUE THREAD

**Issue by rjahrj** [windwp/nvim-ts-autotag#24]
I was wondering if there is auto indenting? 

https://user-images.githubusercontent.com/20189326/130529776-68167595-61ed-477f-bd59-f9aca349a461.mp4

**Comment by windwp** [comment]
this is not belong to this plugin you need 
another plugin nvim-autopairs or mapping cr key with indent

**Comment by Hubro** [comment]
I switched from alvan/vim-closetag to this project today because of tree-sitter support, and this is the only feature I miss.

vim-closetag solved this by letting the user write the closing tag twice. For example, if you write:

```
<script>>
```

Then you get:

```
<script>
    |
</script>
```

This really is a massive time saver, and it would be really great to have an "official" or suggested method for achieving the same result using nvim-ts-autotag.
