### ISSUE TITLE
rust support

### ISSUE THREAD

**Issue by danielnehrig** [windwp/nvim-ts-autotag#55]
the rust framework `yew` supports a macro to do html inside for webassembly
setting the filetype in the config to rust won't allow for tags being closed inside a rust file

**Comment by seblj** [comment]
I looked a bit at this since I also wanted this, and from what I can see the problem is not in this plugin. The problem is with the queries that is set by `nvim-treesitter`. If you comment out this query: https://github.com/nvim-treesitter/nvim-treesitter/blob/a3cef7881ca8e2b8843a4500df44f94311bcc3df/queries/rust/injections.scm#L1-L2 then I believe it should work. It works sometimes without commenting out that line, but I believe that is because of the order of how the queries are applied, and that they are not the same everytime. @danielnehrig
